apiVersion: v2
name: spring-pet-clinic
description: A Helm chart for Pet Clinic app
type: application
version: 0.1.0
appVersion: "1.0"

dependencies:
  - name: customers-service
    version: 0.1.0
    repository: "file://../service-common"
    condition: customer.enabled
  - name: vets-service
    version: 0.1.0
    repository: "file://../service-common"
    condition: vet.enabled
