visits:
  enabled: true
  replicaCount: 1

  image:
    repository: mytruong28022004/spring-petclinic-visits-service
    pullPolicy: Always
    tag: "latest"

  service:
    type: ClusterIP
    port: 80

  ingress:
    enabled: true
    className: "nginx"
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
      - host: spring-pet-clinic.dev
        paths:
          - path: /visits
            pathType: ImplementationSpecific
    tls: []
  env:
      - name: EUREKA_INSTANCE_HOSTNAME
        value: petclinic-visits
customers:
  enabled: true
  replicaCount: 1

  image:
    repository: mytruong28022004/spring-petclinic-customers-service
    pullPolicy: Always
    tag: "latest"
  service:
    type: ClusterIP
    port: 80

  ingress:
    enabled: true
    className: "nginx"
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
      - host: spring-pet-clinic.dev
        paths:
          - path: /customers
            pathType: ImplementationSpecific
    tls: []
  env:
    - name: EUREKA_INSTANCE_HOSTNAME
      value: petclinic-customers
vets:
  enabled: true
  replicaCount: 1

  image:
    repository: mytruong28022004/spring-petclinic-vets-service
    pullPolicy: Always
    tag: "latest"

  service:
    type: ClusterIP
    port: 80

  ingress:
    enabled: true
    className: "nginx"
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
      - host: spring-pet-clinic.dev
        paths:
          - path: /vets
            pathType: ImplementationSpecific
    tls: []
  env:
      - name: EUREKA_INSTANCE_HOSTNAME
        value: petclinic-vets

admin:
  enabled: true
  replicaCount: 1

  image:
    repository: mytruong28022004/spring-petclinic-admin-server
    pullPolicy: Always
    tag: "latest" 

  service:
    type: ClusterIP
    port: 80

  ingress:
    enabled: true
    className: "nginx"
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
      - host: spring-pet-clinic.dev
        paths:
          - path: /admin
            pathType: ImplementationSpecific
    tls: []

  env:
    - name: EUREKA_INSTANCE_HOSTNAME
      value: petclinic-admin

gateway:
  enabled: true
  replicaCount: 1

  image:
    repository: mytruong28022004/spring-petclinic-api-gateway
    pullPolicy: Always
    tag: "latest"

  service:
    type: ClusterIP
    port: 80

  ingress:
    enabled: true
    className: "nginx"
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
      - host: spring-pet-clinic.dev
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls: []

  env:
    - name: EUREKA_INSTANCE_HOSTNAME
      value: petclinic-gateway
config:
  enabled: true
  replicaCount: 1

  image:
    repository: mytruong28022004/spring-petclinic-config-server
    pullPolicy: Always
    tag: "latest"

  service:
    type: ClusterIP
    port: 80

  ingress:
    enabled: false
    className: "nginx"
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts: []
    tls: []

  env:
    - name: EUREKA_INSTANCE_HOSTNAME
      value: petclinic-config

discovery:
  enabled: true
  replicaCount: 1

  image:
    repository: mytruong28022004/spring-petclinic-discovery-server
    pullPolicy: Always
    tag: "latest"

  service:
    type: ClusterIP
    port: 80

  ingress:
    enabled: false
    className: "nginx"
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts: []
    tls: []

  env:
    - name: EUREKA_INSTANCE_HOSTNAME
      value: petclinic-discovery
