visits:
  enabled: true
  replicaCount: 1
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi
  livenessProbe:
    httpGet:
      path: /actuator/health
      port: 8082
    initialDelaySeconds: 120
    periodSeconds: 30
    failureThreshold: 3
  readinessProbe:
    httpGet:
      path: /actuator/health
      port: 8082
    initialDelaySeconds: 90
    periodSeconds: 10
  startupProbe:
    httpGet:
      path: /actuator/health
      port: 8082
    failureThreshold: 30
    periodSeconds: 10
  fullnameOverride: visits-service
  image:
    repository: mytruong28022004/spring-petclinic-visits-service
    pullPolicy: Always
    tag: "latest"
  service:
    type: ClusterIP
    port: 8082
  ingress:
    enabled: false
  env:
    - name: EUREKA_INSTANCE_HOSTNAME
      value: visits-service
    - name: CONFIG_SERVER_URL
      value: http://config-server:8888
    - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
      value: http://discovery-server:8761/eureka/
    - name: SPRING_ZIPKIN_BASE_URL
      value: http://tracing-server:9411

customers:
  enabled: true
  replicaCount: 1
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi
  livenessProbe:
    httpGet:
      path: /actuator/health
      port: 8081
    initialDelaySeconds: 120
    periodSeconds: 30
    failureThreshold: 3
  readinessProbe:
    httpGet:
      path: /actuator/health
      port: 8081
    initialDelaySeconds: 90
    periodSeconds: 10
  startupProbe:
    httpGet:
      path: /actuator/health
      port: 8081
    failureThreshold: 30
    periodSeconds: 10
  fullnameOverride: customers-service
  image:
    repository: mytruong28022004/spring-petclinic-customers-service
    pullPolicy: Always
    tag: "latest"
  service:
    type: ClusterIP
    port: 8081
  ingress:
    enabled: false
  env:
    - name: EUREKA_INSTANCE_HOSTNAME
      value: customers-service
    - name: CONFIG_SERVER_URL
      value: http://config-server:8888
    - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
      value: http://discovery-server:8761/eureka/
    - name: SPRING_ZIPKIN_BASE_URL
      value: http://tracing-server:9411

vets:
  enabled: true
  replicaCount: 1
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi
  fullnameOverride: vets-service
  livenessProbe:
    httpGet:
      path: /actuator/health
      port: 8083
    initialDelaySeconds: 120
    periodSeconds: 30
    failureThreshold: 3
  readinessProbe:
    httpGet:
      path: /actuator/health
      port: 8083
    initialDelaySeconds: 90
    periodSeconds: 10
  startupProbe:
    httpGet:
      path: /actuator/health
      port: 8083
    failureThreshold: 30
    periodSeconds: 10
  image:
    repository: mytruong28022004/spring-petclinic-vets-service
    pullPolicy: Always
    tag: "latest"
  service:
    type: ClusterIP
    port: 8083
  ingress:
    enabled: false
  env:
    - name: EUREKA_INSTANCE_HOSTNAME
      value: vets-service
    - name: CONFIG_SERVER_URL
      value: http://config-server:8888
    - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
      value: http://discovery-server:8761/eureka/
    - name: SPRING_ZIPKIN_BASE_URL
      value: http://tracing-server:9411

admin:
  enabled: true
  replicaCount: 1
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi
  fullnameOverride: admin-server
  image:
    repository: mytruong28022004/spring-petclinic-admin-server
    pullPolicy: Always
    tag: "latest"
  service:
    type: ClusterIP
    port: 9090
  ingress:
    enabled: true
    className: "traefik"
    annotations:
      kubernetes.io/ingress.class: traefik
    hosts:
      - host: spring-pet-clinic-staging-admin.local
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls: []
  env:
    - name: EUREKA_INSTANCE_HOSTNAME
      value: admin-server
    - name: CONFIG_SERVER_URL
      value: http://config-server:8888
    - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
      value: http://discovery-server:8761/eureka/
    - name: SPRING_ZIPKIN_BASE_URL
      value: http://tracing-server:9411

gateway:
  enabled: true
  replicaCount: 1
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi
  fullnameOverride: api-gateway
  image:
    repository: mytruong28022004/spring-petclinic-api-gateway
    pullPolicy: Always
    tag: "latest"
  service:
    type: ClusterIP
    port: 8080
  ingress:
    enabled: true
    className: "traefik"
    annotations:
      kubernetes.io/ingress.class: traefik
    hosts:
      - host: spring-pet-clinic-staging.local
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls: []
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: kubernetes
    - name: EUREKA_INSTANCE_HOSTNAME
      value: api-gateway
    - name: CONFIG_SERVER_URL
      value: http://config-server:8888
    - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
      value: http://discovery-server:8761/eureka/
    - name: SPRING_ZIPKIN_BASE_URL
      value: http://tracing-server:9411

config:
  enabled: true
  replicaCount: 1
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi
  fullnameOverride: config-server
  image:
    repository: mytruong28022004/spring-petclinic-config-server
    pullPolicy: Always
    tag: "latest"
  service:
    type: ClusterIP
    port: 8888
  ingress:
    enabled: false
  env:
    - name: EUREKA_INSTANCE_HOSTNAME
      value: config-server
    - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
      value: http://discovery-server:8761/eureka/

discovery:
  enabled: true
  replicaCount: 1
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi
  fullnameOverride: discovery-server
  image:
    repository: mytruong28022004/spring-petclinic-discovery-server
    pullPolicy: Always
    tag: "latest"
  service:
    type: ClusterIP
    port: 8761
  ingress:
    enabled: false
  env:
    - name: EUREKA_INSTANCE_HOSTNAME
      value: discovery-server
    - name: CONFIG_SERVER_URL
      value: http://config-server:8888
    - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
      value: http://discovery-server:8761/eureka/
    - name: SPRING_ZIPKIN_BASE_URL
      value: http://tracing-server:9411

tracing:
  enabled: true
  replicaCount: 1
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi
  fullnameOverride: tracing-server
  image:
    repository: openzipkin/zipkin
    pullPolicy: Always
    tag: "latest"
  service:
    type: ClusterIP
    port: 9411
  ingress:
    enabled: true
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: kubernetes
    - name: EUREKA_INSTANCE_HOSTNAME
      value: tracing-server
    - name: CONFIG_SERVER_URL
      value: http://config-server:8888
    - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
      value: http://discovery-server:8761/eureka/
    - name: SPRING_ZIPKIN_BASE_URL
      value: http://tracing-server:9411
spring-petclinic-vets-service:
  image:
    tag: v1.0.4
