visits:
  enabled: true
  replicaCount: 1
  podAnnotations:
    helm.sh/hook-weight: "10" # Triển khai sau các service cơ bản
  livenessProbe:
    httpGet:
      path: /actuator/health
      port: 8082
    initialDelaySeconds: 120
    periodSeconds: 30
    failureThreshold: 3
  readinessProbe:
    httpGet:
      path: /actuator/health
      port: 8082
    initialDelaySeconds: 90
    periodSeconds: 10
  startupProbe:
    httpGet:
      path: /actuator/health
      port: 8082
    failureThreshold: 30
    periodSeconds: 10
  initContainers:
    - name: wait-for-dependencies
      image: busybox:1.28
      command: ['sh', '-c', 'until wget -T 5 -qO- http://config-server:8888/actuator/health >/dev/null 2>&1 && wget -T 5 -qO- http://discovery-server:8761/actuator/health >/dev/null 2>&1; do echo "Waiting for config-server and discovery-server"; sleep 10; done;']
  fullnameOverride: visits-service
  image:
    repository: mytruong28022004/spring-petclinic-visits-service
    pullPolicy: Always
    tag: "latest"
  service:
    type: ClusterIP
    port: 8082
  ingress:
    enabled: false
  env:
    - name: EUREKA_INSTANCE_HOSTNAME
      value: visits-service
    - name: CONFIG_SERVER_URL
      value: http://config-server:8888
    - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
      value: http://discovery-server:8761/eureka/
    - name: SPRING_ZIPKIN_BASE_URL
      value: http://zipkin.observability.svc.cluster.local:80
customers:
  enabled: true
  replicaCount: 1
  podAnnotations:
    helm.sh/hook-weight: "10" # Triển khai sau các service cơ bản
  livenessProbe:
    httpGet:
      path: /actuator/health
      port: 8081
    initialDelaySeconds: 120
    periodSeconds: 30
    failureThreshold: 3
  readinessProbe:
    httpGet:
      path: /actuator/health
      port: 8081
    initialDelaySeconds: 90
    periodSeconds: 10
  startupProbe:
    httpGet:
      path: /actuator/health
      port: 8081
    failureThreshold: 30
    periodSeconds: 10
  initContainers:
    - name: wait-for-dependencies
      image: busybox:1.28
      command: ['sh', '-c', 'until wget -T 5 -qO- http://config-server:8888/actuator/health >/dev/null 2>&1 && wget -T 5 -qO- http://discovery-server:8761/actuator/health >/dev/null 2>&1; do echo "Waiting for config-server and discovery-server"; sleep 10; done;']
  fullnameOverride: customers-service
  image:
    repository: mytruong28022004/spring-petclinic-customers-service
    pullPolicy: Always
    tag: "latest"
  service:
    type: ClusterIP
    port: 8081
  ingress:
    enabled: false
  env:
    - name: EUREKA_INSTANCE_HOSTNAME
      value: customers-service
    - name: CONFIG_SERVER_URL
      value: http://config-server:8888
    - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
      value: http://discovery-server:8761/eureka/
    - name: SPRING_ZIPKIN_BASE_URL
      value: http://zipkin.observability.svc.cluster.local:80
vets:
  enabled: true
  replicaCount: 1
  podAnnotations:
    helm.sh/hook-weight: "10" # Triển khai sau các service cơ bản
  livenessProbe:
    httpGet:
      path: /actuator/health
      port: 8083
    initialDelaySeconds: 120
    periodSeconds: 30
    failureThreshold: 3
  readinessProbe:
    httpGet:
      path: /actuator/health
      port: 8083
    initialDelaySeconds: 90
    periodSeconds: 10
  startupProbe:
    httpGet:
      path: /actuator/health
      port: 8083
    failureThreshold: 30
    periodSeconds: 10
  initContainers:
    - name: wait-for-dependencies
      image: busybox:1.28
      command: ['sh', '-c', 'until wget -T 5 -qO- http://config-server:8888/actuator/health >/dev/null 2>&1 && wget -T 5 -qO- http://discovery-server:8761/actuator/health >/dev/null 2>&1; do echo "Waiting for config-server and discovery-server"; sleep 10; done;']
  fullnameOverride: vets-service
  image:
    repository: mytruong28022004/spring-petclinic-vets-service
    pullPolicy: Always
    tag: "v1.0.9"
  service:
    type: ClusterIP
    port: 8083
  ingress:
    enabled: false
  env:
    - name: EUREKA_INSTANCE_HOSTNAME
      value: vets-service
    - name: CONFIG_SERVER_URL
      value: http://config-server:8888
    - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
      value: http://discovery-server:8761/eureka/
    - name: SPRING_ZIPKIN_BASE_URL
      value: http://zipkin.observability.svc.cluster.local:80
admin:
  enabled: true
  replicaCount: 1
  podAnnotations:
    helm.sh/hook-weight: "15" # Triển khai sau các service khác
  livenessProbe:
    httpGet:
      path: /actuator/health
      port: 9090
    initialDelaySeconds: 120
    periodSeconds: 30
    failureThreshold: 3
  readinessProbe:
    httpGet:
      path: /actuator/health
      port: 9090
    initialDelaySeconds: 90
    periodSeconds: 10
  startupProbe:
    httpGet:
      path: /actuator/health
      port: 9090
    failureThreshold: 30
    periodSeconds: 10
  initContainers:
    - name: wait-for-dependencies
      image: busybox:1.28
      command: ['sh', '-c', 'until wget -T 5 -qO- http://config-server:8888/actuator/health >/dev/null 2>&1 && wget -T 5 -qO- http://discovery-server:8761/actuator/health >/dev/null 2>&1; do echo "Waiting for config-server and discovery-server"; sleep 10; done;']
  fullnameOverride: admin-server
  image:
    repository: mytruong28022004/spring-petclinic-admin-server
    pullPolicy: Always
    tag: "latest"
  service:
    type: ClusterIP
    port: 9090
  ingress:
    enabled: true
    className: "traefik"
    annotations:
      kubernetes.io/ingress.class: traefik
    hosts:
      - host: spring-pet-clinic-staging-admin.local
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls: []
  env:
    - name: EUREKA_INSTANCE_HOSTNAME
      value: admin-server
    - name: CONFIG_SERVER_URL
      value: http://config-server:8888
    - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
      value: http://discovery-server:8761/eureka/
    - name: SPRING_ZIPKIN_BASE_URL
      value: http://zipkin.observability.svc.cluster.local:80
gateway:
  enabled: true
  replicaCount: 1
  podAnnotations:
    helm.sh/hook-weight: "10" # Triển khai sau các service cơ bản
  livenessProbe:
    httpGet:
      path: /actuator/health
      port: 8080
    initialDelaySeconds: 120
    periodSeconds: 30
    failureThreshold: 3
  readinessProbe:
    httpGet:
      path: /actuator/health
      port: 8080
    initialDelaySeconds: 90
    periodSeconds: 10
  startupProbe:
    httpGet:
      path: /actuator/health
      port: 8080
    failureThreshold: 30
    periodSeconds: 10
  initContainers:
    - name: wait-for-dependencies
      image: busybox:1.28
      command: ['sh', '-c', 'until wget -T 5 -qO- http://config-server:8888/actuator/health >/dev/null 2>&1 && wget -T 5 -qO- http://discovery-server:8761/actuator/health >/dev/null 2>&1; do echo "Waiting for config-server and discovery-server"; sleep 10; done;']
  fullnameOverride: api-gateway
  image:
    repository: mytruong28022004/spring-petclinic-api-gateway
    pullPolicy: Always
    tag: "latest"
  service:
    type: ClusterIP
    port: 8080
  ingress:
    enabled: true
    className: "traefik"
    annotations:
      kubernetes.io/ingress.class: traefik
    hosts:
      - host: spring-pet-clinic-staging.local
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls: []
  env:
    - name: EUREKA_INSTANCE_HOSTNAME
      value: api-gateway
    - name: CONFIG_SERVER_URL
      value: http://config-server:8888
    - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
      value: http://discovery-server:8761/eureka/
    - name: SPRING_ZIPKIN_BASE_URL
      value: http://zipkin.observability.svc.cluster.local:80
config:
  enabled: true
  replicaCount: 1
  podAnnotations:
    helm.sh/hook-weight: "-10" # Triển khai đầu tiên
  livenessProbe:
    httpGet:
      path: /actuator/health
      port: 8888
    initialDelaySeconds: 60
    periodSeconds: 30
    failureThreshold: 3
  readinessProbe:
    httpGet:
      path: /actuator/health
      port: 8888
    initialDelaySeconds: 30
    periodSeconds: 10
  startupProbe:
    httpGet:
      path: /actuator/health
      port: 8888
    failureThreshold: 15
    periodSeconds: 10
  fullnameOverride: config-server
  image:
    repository: mytruong28022004/spring-petclinic-config-server
    pullPolicy: Always
    tag: "latest"
  service:
    type: ClusterIP
    port: 8888
  ingress:
    enabled: false
  env:
    - name: EUREKA_INSTANCE_HOSTNAME
      value: config-server
    - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
      value: http://discovery-server:8761/eureka/
discovery:
  enabled: true
  replicaCount: 1
  podAnnotations:
    helm.sh/hook-weight: "-5" # Triển khai thứ hai
  livenessProbe:
    httpGet:
      path: /actuator/health
      port: 8761
    initialDelaySeconds: 60
    periodSeconds: 30
    failureThreshold: 3
  readinessProbe:
    httpGet:
      path: /actuator/health
      port: 8761
    initialDelaySeconds: 30
    periodSeconds: 10
  startupProbe:
    httpGet:
      path: /actuator/health
      port: 8761
    failureThreshold: 15
    periodSeconds: 10
  initContainers:
    - name: wait-for-config
      image: busybox:1.28
      command: ['sh', '-c', 'until wget -T 5 -qO- http://config-server:8888/actuator/health >/dev/null 2>&1; do echo "Waiting for config-server"; sleep 10; done;']
  fullnameOverride: discovery-server
  image:
    repository: mytruong28022004/spring-petclinic-discovery-server
    pullPolicy: Always
    tag: "latest"
  service:
    type: ClusterIP
    port: 8761
  ingress:
    enabled: false
  env:
    - name: EUREKA_INSTANCE_HOSTNAME
      value: discovery-server
    - name: CONFIG_SERVER_URL
      value: http://config-server:8888
    - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
      value: http://discovery-server:8761/eureka/
    - name: SPRING_ZIPKIN_BASE_URL
      value: http://zipkin.observability.svc.cluster.local:80
