apiVersion: v1
kind: Service
metadata:
  name: {{ include "service-common.fullname" . }}
  labels:
    {{- include "service-common.labels" . | nindent 4 }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "{{ .Values.service.port }}"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "service-common.selectorLabels" . | nindent 4 }}
