apiVersion: agrocd.io/v1alpha1
kind: Application
metadata:
  name: spring-pet-clinic-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/thmthu/CD-for-pet-clinic'
    targetRevision: HEAD
    path: spring-pet-clinic
    helm:
      valueFiles:
        - values_dev.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true